# Generated by Django 5.1.3 on 2024-11-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=17)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
